rules = [
  OrganizeImports
  RedundantSyntax
  DisableSyntax
  LeakingImplicitClassVal
  NoValInForComprehension
]

OrganizeImports.expandRelative   = true
OrganizeImports.removeUnused     = true
OrganizeImports.targetDialect    = Scala2
OrganizeImports.groupedImports   = AggressiveMerge

DisableSyntax.noVars         = true
DisableSyntax.noNulls        = true
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noIsInstanceOf = true
DisableSyntax.noReturns      = true
DisableSyntax.noXml          = true
